import React from 'react';
import axios from 'axios';

const AUTOGEN_API = "https://yxhgluw0ig.execute-api.us-west-2.amazonaws.com/prod/api/general/hello";
const CUSTOM_API = "https://api.johnhubberts.com/api/general/hello";

export default class ConnectivityChecker extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      autogenMessage: "Request to API gateway autogenerated endpoint is pending",
      customMessage: "Request to custom API domain name is pending"
    };
  }

  componentDidMount() {
    axios.get(AUTOGEN_API)
      .then(() => {
        this.setState({autogenMessage: "Autogenerated endpoint is accessible"})
      })
      .catch(error => {
        this.setState({autogenMessage: `Autogenerated endpoint is inaccessible. Message is ${error}`})
      });

    axios.get(CUSTOM_API)
      .then(() => {
        this.setState({customMessage: "Custom endpoint is accessible"})
      })
      .catch(error => {
        this.setState({customMessage: `Custom endpoint is inaccessible. Message is ${error}`})
      });
  }

  render() {
    return (
      <div>
        <p>{this.state.autogenMessage}</p>
        <p>{this.state.customMessage}</p>
      </div>
    )
  }
}